In [1]:
import gym
import numpy as np
import os

In [2]:
env = gym.make('FrozenLake-v1',
            is_slippery=False,
            render_mode="human" )


In [3]:
os.getcwd()

'c:\\Users\\a\\Desktop\\NUS\\Academics\\Y4S2\\ME5406\\frozen_lake'

In [4]:
qtable = np.load(
    "data/default/ql0001/qtable_final.npy"
)
action_size = env.action_space.n
state_size = env.observation_space.n

SIZE = 4
NOUP = [i for i in range(SIZE)]
NODOWN = [state_size-1-i for i in range(SIZE)]
NOLEFT = [i*SIZE for i in range(SIZE)]
NORIGHT = [i*SIZE + SIZE for i in range(SIZE)]


def possible_actions(state):
    action_list = [0,1,2,3]
    if state in NOLEFT:
        action_list.remove(0)
    if state in NODOWN:
        action_list.remove(1)
    if state in NORIGHT:
        action_list.remove(2)
    if state in NOUP:
        action_list.remove(3)
    return action_list



FileNotFoundError: [Errno 2] No such file or directory: 'data/default/ql0001qtable_final.npy'

In [ ]:
print(qtable)

[[ 0.          0.10321937  0.47744349  0.        ]
 [-0.362025   -1.          0.69654485  0.        ]
 [-0.08430015  0.7579927  -0.01734135  0.        ]
 [ 0.16806126 -1.         -0.53656799  0.        ]
 [ 0.         -0.28030741  0.          0.12391431]
 [ 0.          0.          0.          0.        ]
 [-1.          0.85706634 -1.          0.30848517]
 [ 0.          0.          0.          0.        ]
 [ 0.         -1.          0.         -0.13961527]
 [-0.4084912  -0.11669732  0.75094908 -1.        ]
 [ 0.40171613  0.9422577  -1.          0.35914839]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [-1.          0.          0.88651576  0.12211553]
 [ 0.69078431  0.          1.          0.70095818]
 [ 0.          0.          0.          0.        ]]


In [ ]:
statestate = env.reset()
state = statestate[0]
total_rewards = 0

env.render()
done = False


action_list = possible_actions(state) 
row = list(qtable[state])
goodq = []
for i in action_list:
    goodq.append(row[i])

max_value = np.max(goodq)
max_indices = np.where(row == max_value)[0]
action = max_indices[0]

# action=np.argmax(qtable[state])

input()
while not done:

    new_state, reward, done, truncated, info = env.step(action)

    state = new_state
    action_list = possible_actions(state) 
    row = list(qtable[state])
    goodq = []
    for i in action_list:
        goodq.append(row[i])

    max_value = np.max(goodq)
    max_indices = np.where(row == max_value)[0]
    action = max_indices[0]    
    input()

env.close()


c:\Users\a\.conda\envs\fl_39\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


<bound method Wrapper.close of <TimeLimit<OrderEnforcing<PassiveEnvChecker<FrozenLakeEnv<FrozenLake-v1>>>>>>

In [ ]:
test=9

In [ ]:
"%04d" % test

'0009'